---
format: html

title: "Map"
---

```{r}

#install.packages(googlesheets4)

library(tidyverse)

library(maps)

library(googlesheets4)

class_info <- read_sheet("<https://docs.google.com/spreadsheets/d/1XOAFQvBcFvhKwEl5xH6l3nRJK2Wk0hWZ18S9kAZclQ0/edit?usp=sharing>") |> janitor::clean_names()
!
  # selecting only the column we are interested in and making it into a vector. country_vector \<- as.vector( class_info \|\> select("country"))

```

```{r}
class_info |>
  ggplot (mapping = aes(x = silblings)) + 
  geom_bar ( fill= "brown" ) +
  labs ( y = "number of people",
         x = "number of siblings",
        title= "SDS 192 students siblings",
         caption=  "alex", #author
         subtitle= "SDS Fall 2024" )
          
            
         
             
             
             
             
             
```

```{r}
class_info |>
  filter (!is.na (other_sds_courses)) |>
  ggplot (map = aes(x =other_sds_courses)) +
  geom_bar ( fill= "black") +
  labs ( y= "number of people",
         x= " No of SDS classes taken",
         title= "other SDS classes taken by SDS 192 students",
         caption= "Sabzara Ali")
  filter (!is.na (other_sds_courses))
```

```{r}
 class_info |>
   ggplot(map= aes(x= silblings, y= height)) +
   geom_point (fill="black") 
   labs( y =  "Height",
         x = "No of siblings",
         title= "siblings and height",
         caption = "Sabzara Ali")
   
   
   
 

```
